# Generated by Django 3.2 on 2022-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainrecord',
            old_name='Status',
            new_name='Resolved',
        ),
    ]
